server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  security:
#    user:
#      name: username
#      password: 123456
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url : jdbc:h2:tcp://localhost/~/data/springdb
    username: sa
    password: